"""Convert the MFDS food database workbooks into the app's catalog module.

Run manually when a newer workbook is published:
    python3 scripts/import_food_db.py

The workbooks live in "docs/FOOD DATABASE/" and are not committed; only the
generated js/foods-kr.js is. Values are copied from the source columns without
estimation. See docs/FOOD_DATA.md.
"""

import json
import re
import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "FOOD DATABASE" / "20250408_음식DB.xlsx"
TARGET = ROOT / "js" / "foods-kr.js"

COL = {
    "name": 1,
    "basis": 16,
    "kcal": 17,
    "protein": 19,
    "fat": 20,
    "carbs": 22,
    "group": 7,
    "weight": 153,
}
WEIGHT = re.compile(r"^([0-9]+(?:\.[0-9]+)?)\s*(g|ml)$", re.IGNORECASE)


def number(value):
    if value is None:
        return None
    text = str(value).strip()
    if text in ("", "-", "해당없음", "N/A"):
        return None
    try:
        return round(float(text), 3)
    except ValueError:
        return None


def label(name):
    # Source names read "피자_슈퍼 디럭스"; the underscore separates the dish
    # group from the specific product.
    return name.replace("_", " · ", 1).strip()


def main():
    if not SOURCE.exists():
        sys.exit(f"워크북을 찾을 수 없습니다: {SOURCE}")
    sheet = openpyxl.load_workbook(SOURCE, read_only=True).active

    items, seen, skipped = [], set(), 0
    for row in sheet.iter_rows(min_row=2, values_only=True):
        name = (row[COL["name"]] or "").strip()
        kcal = number(row[COL["kcal"]])
        if not name or kcal is None or name in seen:
            skipped += 1
            continue
        seen.add(name)

        basis_unit = "ml" if str(row[COL["basis"]]).endswith("ml") else "g"
        macros = [
            number(row[COL[key]]) for key in ("protein", "carbs", "fat")
        ]
        match = WEIGHT.match(str(row[COL["weight"]] or "").strip())
        grams = float(match.group(1)) if match else None

        if grams and grams != 100:
            # One serving, scaled from the published per-100 basis.
            scale = grams / 100
            values = [round(kcal * scale, 2)] + [
                None if m is None else round(m * scale, 2) for m in macros
            ]
            items.append(
                [
                    f"{label(name)} · 1인분 {match.group(1)}{match.group(2)}",
                    *values,
                    1,
                    "개",
                    row[COL["group"]] or "",
                ]
            )
        else:
            items.append(
                [label(name), kcal, *macros, 100, basis_unit, row[COL["group"]] or ""]
            )

    payload = json.dumps(items, ensure_ascii=False, separators=(",", ":"))
    TARGET.write_text(
        "// Generated by scripts/import_food_db.py. Do not edit by hand.\n"
        "// 식품의약품안전처 식품영양성분 데이터베이스 (음식DB, 2025-04-08).\n"
        "// [name, kcal, protein, carbs, fat, baseAmount, baseUnit, group]\n"
        "const rows = " + payload + ";\n\n"
        "export const KOREAN_FOODS = rows.map(\n"
        "  ([name, kcal, protein, carbs, fat, baseAmount, baseUnit, group], index) =>\n"
        "    Object.freeze({\n"
        "      id: `mfds-${index}`,\n"
        "      name,\n"
        "      kcal,\n"
        "      protein,\n"
        "      carbs,\n"
        "      fat,\n"
        "      keywords: group,\n"
        "      baseAmount,\n"
        "      baseUnit,\n"
        '      source: "식품의약품안전처 식품영양성분DB · 음식DB 2025-04-08",\n'
        '      sourceUrl: "https://various.foodsafetykorea.go.kr/nutrient/",\n'
        "    }),\n"
        ");\n",
        encoding="utf-8",
    )
    print(f"{len(items)}종 생성 · 건너뜀 {skipped} · {TARGET.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
